workflows:
  flutter-apk:
    name: Build APK for D'Maria Spa
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Ensure Flutter project structure
        script: |
          if [ ! -d "android" ]; then
            flutter create . --project-name d_maria_spa
          fi
          flutter pub get
      - name: Build release APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - "you@example.com"
        notify:
          success: true
          failure: true
